### ISSUE TITLE
Consider changing json keys

### ISSUE THREAD

**Issue by mrexodia** [ioncodes/dnpatch.script#1]
I think the patch scripts will be more readable is you write out the json keys fully, eg "namespace" instead of "ns".

Or at least allow people to write out the keys...

**Comment by ioncodes** [comment]
Thanks for this! I actually wanted to do that, but I forgot to change it. I used 2 letters to simplify debugging.

**Comment by ioncodes** [comment]
Fixed it, thanks for the reminder!
